version: "3"

tasks:
  generate:
    cmds:
      - go generate ./...

  assets:
    cmds:
      - mkdir -p ui/assets/js
      - cp node_modules/htmx.org/dist/htmx.min.js ui/assets/js

  build:
    desc: Builds the service
    deps:
      - generate
      - assets
    cmds:
      - go build .

  run:
    desc: Runs the service
    deps:
      - generate
      - assets
    cmds:
      - go run .

  run:dev:
    desc: Runs the service with watch enabled
    cmds:
      - templ generate --watch --cmd="go run ."
